version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  user-auth:
    build: ./user-auth
    ports:
      - "3002:3002"
    env_file:
      - ./user-auth/.env
    depends_on:
      - mongo
      - notification-service

  notification-service:
    build: ./notification
    ports:
      - "3003:3003"
    env_file:
      - ./notification/.env

  user-profile:
    build: ./user-profile
    ports:
      - "3001:3001"
    env_file:
      - ./user-profile/.env
    depends_on:
      - mongo
